#---
#  beans: 
#    xmlns: "http://www.springframework.org/schema/beans"
#    xmlns:xsi: "http://www.w3.org/2001/XMLSchema-instance"
#    xmlns:context: "http://www.springframework.org/schema/context"
#    xmlns:p: "http://www.springframework.org/schema/p"
#    xmlns:tx: "http://www.springframework.org/schema/tx"
#    xsi:schemaLocation: "http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd   http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-4.3.xsd   http://www.springframework.org/schema/tx http://www.springframework.org/schema/tx/spring-tx-4.3.xsd"
#    context:annotation-config: {}
#    tx:annotation-driven: {}
#    bean: 
#      - 
#        id: "dataSource"
#        class: "org.springframework.jdbc.datasource.DriverManagerDataSource"
#        property: 
#          - 
#            name: "driverClassName"
#            value: "com.mysql.cj.jdbc.Driver"
#          - 
#            name: "username"
#            value: "root"
#          - 
#            name: "password"
#            value: "Bkt@123"
#          - 
#            name: "url"
#            value: "jdbc:mysql://localhost:3306/springhibernate"
#      - 
#        id: "sessionFactory"
#        class: "org.springframework.orm.hibernate5.LocalSessionFactoryBean"
#        property: 
#          - 
#            name: "dataSource"
#            ref: "dataSource"
#          - 
#            name: "hibernateProperties"
#            props: 
#              prop: 
#                - 
#                  key: "hibernate.hbm2ddl.auto"
#                  $t: "update"
#                - 
#                  key: "hibernate.dialect"
#                  $t: "org.hibernate.dialect.MySQL5Dialect"
#                - 
#                  key: "hibernate.show_sql"
#                  $t: "true"
#          - 
#            name: "annotatedClasses"
#            list: 
#              value: "com.bean.Student"
#      - 
#        id: "transactionManager"
#        class: "org.springframework.orm.hibernate5.HibernateTransactionManager"
#        property: 
#          name: "sessionFactory"
#          ref: "sessionFactory"
#      - 
#        id: "hibernateTemplate"
#        class: "org.springframework.orm.hibernate5.HibernateTemplate"
#        property: 
#          name: "sessionFactory"
#          ref: "sessionFactory"
#      - 
#        id: "memberDao"
#        class: "com.dao.MemberDao"
#        property: 
#          name: "hibernateTemplate"
#          ref: "hibernateTemplate"
